---

- name: Setup hardened ssh configuration file
  template:
          src: templates/sshd_config.j2
          dest: /etc/ssh/sshd_config
          owner: root
          group: root
          mode: 0644
          validate: '/usr/sbin/sshd -T -f %s'
  tags: ssh

- name: Restart ssh daemon
  systemd:
          name: sshd
          state: restarted
  tags: ssh
