---

- name: Setup hardened ssh configuration file
  template:
          src: templates/sshd_config.j2
          dest: /etc/ssh/sshd_config
          owner: root
          group: root
          mode: 0644
          validate: '/usr/sbin/sshd -T -f %s'
  tags: ssh

- name: Change SELinux to allow non-standard port (RHEL specific)
  seport:
          ports: "{{ port }}"
          proto: tcp
          setype: ssh_port_t
          state: present
  when: ansible_os_family == 'RedHat'

- name: Restart ssh daemon
  systemd:
          name: sshd
          state: restarted
  tags: ssh
