---
- include_vars: vars/vars.yaml

- name: Update package repo & install required packages
  apt:
          name: "{{ required_packages_deb }}"
          state: present
  tags: packages
  when: ansible_os_family == 'Debian'

- name: Install dependencies for installing PHP7.0 (RHEL specific)
  command: yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  when: ansible_os_family == 'RedHat'

- name: Update package repo & install required packages
  yum:
          name: "{{ required_packages_rhel }}"
          state: present
  tags: packages
  when: ansible_os_family == 'RedHat'

- name: Enable Remi's repo as default for installing PHP (RHEL specific)
  command: yum-config-manager --enable remi-php70
  when: ansible_os_family == 'RedHat'
